Happy-Algorithms-League/hal-cgp

gp/abstract_individual.py
gp/abstract_population.py
gp/cgp_genome.py
gp/cgp_graph.py
gp/cgp_individual.py
gp/cgp_node.py
gp/cgp_population.py
gp/cgp_primitives.py
gp/ea/mu_plus_lambda.py
gp/hl_api.py
gp/utils.py

This PR adds docstrings to all public functions and methods in the `gp` module. 
I did not create docstring for private methods (starting with `_` or `__`) for now. Some functions were left undocumented because they might be removed.
This addresses #2 .

Add docstrings to all public functions and class methods.

---

examples/example_evo_regression.py

This PR updates the `example_evo_regression` script. This addresses #9 partially.
@jakobj : For the "hard" example in the script, the evolution notoriously gets stuck with a constant expression. I tried a bunch of different parameters but couldn't get anywhere. Any ideas?

Update, clean up and refactor example_evo_regression script

---

.flake8
.travis.yml
examples/example_evo_regression.py
examples/example_random_regression.py
test/test_binary_population.py
test/test_cgp_evolve.py
test/test_cgp_genome.py
test/test_cgp_graph.py
test/test_cgp_individual.py
test/test_cgp_node.py
test/test_cgp_primitives.py
test/test_ea_mu_plus_lambda.py
test/test_utils.py

Do not explicitly manipulate sys.path

---

test/test_cgp_node.py

Add tests for CGPDiv, CGPPow

---

examples/example_evo_regression.py

i've adjusted the hard function such that it's still difficult to fit, but is possible within 1000 generations as specified. in addition the example now makes use of parallel processes

Make hard example solvable and make use of n_processes

---

gp/hl_api.py

@mschmidt87 could you please check whether this resolves your printing issue? it works on my system
fixes #11

Set flush to true in print progress

---

gp/hl_api.py

Do not print champion.idx when printing progress

---

gp/__init__.py
gp/cgp_node.py
gp/cgp_node_factories.py
test/test_cgp_node.py
test/test_cgp_node_factories.py

Move ConstantFloat class factory to separate file

---

test/test_cartesian_graph.py
test/test_evolve.py
test/test_hl_api.py
test/test_node.py
test/test_node_factories.py

Replace assert with approximate limits by pytest.approx constructions

---

examples/example_caching.py

Provide an example using the caching decorator

---

gp/cartesian_graph.py
gp/node.py
test/test_cartesian_graph.py

Increase number of characters per node to avoid cutting off of node names
Add test
Fix unrelated bug in __repr__ method node class
Fixes #30

Fix bug in pretty representation of graph (#30)

---

test/conftest.py
test/test_population.py

Fixes #54 .
The tests are quite simple at the moment, suggestions for improved tests are welcome.

Add tests for population class, add fixtures for population tests

---

gp/individual.py

Add to_torch method to Individual

---

.travis.yml

This PR makes travis install all optional dependencies and closes #78 .

Install all optional dependencies in travis

---

extra-requirements.txt
requirements.txt

Add versions to (extra)requirements

---

examples/example_evo_regression.py

- make example deterministic
- suppress warning caused by zero division
- increase tournament size to 2 to encourage competition during
selection
- separate parameters according to convention
do you remember why we chose a tournament size of 1 @mschmidt87 ? this just picks offsprings randomly from the parent population. in the (very limited) tests that i've run this seems to slow down evolution.

Fix evo example

---

gp/cartesian_graph.py
test/test_cartesian_graph.py

Fix pretty_str to not cut of inputs/outputs if their count exceed n_rows

---

test/test_local_search.py

Add test for gradient-based local search

---

gp/genome.py
test/test_genome.py

Fix typo "permissable" -> "permissible"

---

gp/ea/mu_plus_lambda.py

as the title suggests :)
fixes #111

Add type hints to MuPlusLambda

---

cgp/utils.py

Add typing to utils.py

---

examples/example_caching.py
examples/example_differential_evo_regression.py
examples/example_evo_regression.py

i've adapted the mutation rate to more reasonable values (0.5 -> 0.05). also needed to increase the number of cols in `example_evo_regression.py` to make it converge in a reasonable number of generations.
fixes #121

Fix examples

---

cgp/cartesian_graph.py
cgp/genome.py
cgp/individual.py

as discussed. also removes redundant docstrings.
fixes #125

Simplify Individual: move mutate() to Genome

---

.travis.yml

Change mode of installation in travis CI

---

README.md

Add installation instructions for individual extra requirements

---

test/test_node.py

while some nodes were tested only for returning the correct values when calling the graph, others were only tested for some `to_...` functions. this PR unifies the tests, such that all nodes are tested for all supported uses.

Unify node tests

---

cgp/genome.py

Fix type of `levels_back` and update doc

---

examples/example_mountain_car.py

building on #204 this PR makes the Mountain Car example reproducible by fixing the environment seed before the first observation is obtained. in addition, it fixes a couple of minor issues in this example and slightly adapts parameters to make sure a good solution is found in reasonable time.
closes #202

Make Mountain Car example deterministic

---

cgp/genome.py

Use logical and, and reuse existing functions in helper functions of `Genome`

---

cgp/population.py

Assign parent_idx = -1 to individuals not created from other individuals via clone

---

cgp/__init__.py
setup.py

Fix keywords and short description

---

extra-requirements.txt

This PR fixes #228  by updating the sympy version to 1.6.1.

Update sympy version to fix problem with evaluate(False) context

---

examples/example_minimal.py

please suggest any further simplification that comes to mind.
closes #221

Add minimal regression example

---

cgp/population.py

mypy was complaining about this. necessary for CI to pass.

Make sure fitness is not None when determining champion

---

cgp/utils.py
test/test_utils.py

So far, always the first entry in the cache was used to compare the return values of different functions sharing the same cache. If this values happens to be non-finite, e.g., `np.inf`, objectives which in general have different return values, but both return non-finite value for this specific input, can be determined to be consistent.
This PR makes sure this does not happen by looking for cache entries with finite values when checking cache consistency.

Make sure cache consistency uses finite return values

---

cgp/population.py
test/test_population.py

In some cases, one may want to provide prior information about suitable functions, e.g., to search for functions which achieve higher fitness than this minimal solution.
This PR introduces an extension of the `Population` API which introduces a callback that is called for each member of the initial parent population. This allows setting the dna of these individuals, thereby providing an initial solution.
Please do not only review with respect to correctness, but also in terms of usability @mschmidt87 @HenrikMettler

Introduce callback to initialize individuals of the initial parent population

---

cgp/ea/mu_plus_lambda.py
cgp/population.py
examples/example_caching.py
examples/example_differential_evo_regression.py
examples/example_evo_regression.py
examples/example_fec_caching.py
examples/example_hurdles.py
examples/example_minimal.py
examples/example_mountain_car.py
examples/example_multi_genome.py
examples/example_parametrized_nodes.py
examples/example_piecewise_target_function.py
examples/example_reorder.py
test/conftest.py
test/test_ea_mu_plus_lambda.py
test/test_population.py

Moves the parameter mutation_rate from population to mu_plus_lambda. Closes #256

Move mutation_rate into EA

---

cgp/ea/mu_plus_lambda.py

Check number of objectives matches number of specified hurdle percentiles

---

cgp/ea/mu_plus_lambda.py
cgp/genome.py
cgp/individual.py
cgp/local_search/evolution_strategies.py
cgp/population.py
cgp/utils.py

As the title promises :)
closes #297

Use Optional[<type>] instead of Union[<type>, None]

---

cgp/__init__.py

Bump version to 0.3.0 to prepare the release.

Bump version to 0.3.0

---

test/test_hl_api.py
test/test_individual.py
test/test_utils.py

- avoid using `min_fitness`
- avoid global variables which start with `Test`
closes #304

Fix warnings in testsuite

---

README.rst
cgp/hl_api.py
test/test_hl_api.py

as the title suggests.
closes #301

Remove min_fitness arg from hl api

---

cgp/hl_api.py

as the title suggests.
closes #327

Check max_generations/max_objective_calls against maximal integer

---

cgp/genome.py
test/test_genome.py

like the title suggests.
closes #306

Raise RuntimeError when trying to access uninitialized dna

---

test/conftest.py
test/test_cartesian_graph.py
test/test_ea_mu_plus_lambda.py
test/test_genome.py
test/test_hl_api.py
test/test_individual.py
test/test_node.py
test/test_population.py
test/test_utils.py

- replace numpy global rng
- replace torch global rng
closes #305

Avoid global rngs in testsuite

---

.pre-commit-config.yaml

As the title says. Closes #337

Change black version to 19.10b

---

README.rst
cgp/ea/mu_plus_lambda.py
cgp/genome.py
cgp/hl_api.py
cgp/population.py
examples/example_caching.py
examples/example_differential_evo_regression.py
examples/example_evo_regression.py
examples/example_fec_caching.py
examples/example_hurdles.py
examples/example_local_search_evolution_strategies.py
examples/example_minimal.py
examples/example_mountain_car.py
examples/example_multi_genome.py
examples/example_parametrized_nodes.py
examples/example_piecewise_target_function.py
examples/example_reorder.py
test/test_hl_api.py
test/test_utils.py

as the title suggests
we could also simplify the minimal example a lot with these new defaults. what do you think?
closes #307

Provide somewhat sensible defaults for all hyperparameters

---

cgp/ea/mu_plus_lambda.py
cgp/individual.py
test/test_ea_mu_plus_lambda.py

as the title suggests. this should help to pinpoint bugs in objective functions.
closes #309

Raise exception if fitness is None after calls to objectives

---

cgp/genome.py
test/test_genome.py

In some use cases it is nice to set (one of) the output(s) to a prior. One way of doing this is by inserting a dna sequence corresponding to the prior at the first internal node(s). `slice_dna` gives this possibility, without requiring the user to set the full dna. 
Marked as draft, since test coverage is minimal and code not optimized. 
(Note: I also looked at implementing the prior from a function/sympy string, however this seems quite tedious, especially if the prior contains more than 1 operation. This implementation at least circumvents the need to set the full dna :) )
closes #317 (by circumventing the issue)

Set-output-expression: Enable setting of a prior to an output node

---

cgp/ea/mu_plus_lambda.py

Add comment explaining sorting logic in MuPlusLambda

---

examples/example_evo_regression_numpy.py

It seems we were missing an example of how one would use NumPy to vectorize function evaluations. This PR contains such an example as an extension of our standard example.

Add simple example using NumPy to vectorized function evaluation

---

examples/example_caching.py
examples/example_differential_evo_regression.py
examples/example_evo_regression.py
examples/example_evo_regression_numpy.py
examples/example_fec_caching.py
examples/example_hurdles.py
examples/example_local_search_evolution_strategies.py
examples/example_mountain_car.py
examples/example_multi_genome.py
examples/example_parametrized_nodes.py
examples/example_piecewise_target_function.py
examples/example_reorder.py

As the title suggests. This should make all examples easier to understand.
fixes #346

Use default parameters where possible in examples

---

cgp/hl_api.py

(as the title suggests)
test suite should work again now

Fix mypy (avoid implicit `Optional`s)

---

cgp/ea/mu_plus_lambda.py
cgp/hl_api.py
extra-requirements.txt
requirements.txt
test/test_node.py

as the title suggests. partly addresses #369

Support more recent version of numpy

---

docs/conf.py
examples/example_initialize_individuals.py

Add example to show how to initialize individuals of the initial generation

---

cgp/genome.py

Make sure `permissible_values` is a list of arrays
