gp/cgp_graph.py, test/test_cgp_evolve.py, test/test_cgp_graph.py
Renames the `compile_` functions to `to_` and removes the duplicate functions in the `CGPGraph` class. Adapts the tests as well.
This addresses and fixes #13 .
=> Rename compile functions in CGPGraph class

setup.py
This PR adds a setup script to the repository so that the library can be installed via `pip install .` .
This fixes #7 .
=> Add setup.py to make library installable via pip

gp/abstract_individual.py, gp/cgp_graph.py, gp/cgp_node.py
As the PR title says: it simply replaces all formatted strings by f-strings, which is the more modern and readable syntax.
Fixes #21 .
=> Replace all formatted strings by f-strings

examples/example_evo_regression.py, gp/hl_api.py, test/test_utils.py
Only providing a callback provides more flexibility and is cleaner to implement.
closes #8
=> Replace record_history with callback

gp/cartesian_graph.py, test/test_cartesian_graph.py
Without these checks one can produce quite strange error messages:
```bash
File "<string>", line 1, in _f
IndexError: list index out of range
```
=> Add checks for input dimension in python function and pytorch class

gp/utils.py, test/test_utils.py
As proposed by @mschmidt87 this PR implements a consistency check in the disk cache decorator. It checks for consistency of arguments, keyword arguments and return values to avoid reusing the disk cache for different functions.
Unfortunately flake8 complains about a "too complex" function (`disk_cache`). Any idea how to address this @mschmidt87? Move the whole decorator to a separate module? I like that the required functions are only defined within the decorator function, hence not visible outside.
fixes #67
=> Add consistency checks to disk cache decorator

gp/cartesian_graph.py, gp/node.py, test/test_cartesian_graph.py
This does not seem to be used anywhere and is unnecessary in the first place: the `format_output_str...` functions  all modify the `_output_str` member prior to generating the full expression. Can be re-added if the need arises.
=> Remove unnecessary `output_str_torch` property

test/conftest.py, test/test_cartesian_graph.py, test/test_ea_mu_plus_lambda.py, test/test_genome.py, test/test_hl_api.py, test/test_individual.py, test/test_node.py, test/test_primitives.py, test/test_utils.py
as the title suggests, this PR replaces the stochastic random seed with a fixed random seed from `conftest` in all tests. it also uses a few more fixtures where appropriate.
this should avoid the random failures of tests possibly responsible for #75
=> Use fixed rng seed for tests

examples/example_caching.py, gp/utils.py
This PR avoids using a nested function in the caching example thus following the recommendation from the updated docstring ;) 
[edit]
for completeness, quoted from the discussion below:
> it's a scope issue: nested functions are defined and hence decorated each time the outer function is called. as the consistency check is performed on the first execution after decoration it is hence executed on every outer function call which should not be the case for efficient caching
[/edit]
=> Fix caching example and update decorator docstring

.travis.yml, README.md, extra-requirements.txt, gp/cartesian_graph.py, gp/genome.py, gp/hl_api.py, gp/local_search/gradient_based.py, gp/node.py, gp/population.py, gp/primitives.py, mypy.ini, test/test_cartesian_graph.py, test/test_genome.py, test/test_individual.py, test/test_local_search.py, test/test_node.py, test/test_node_factories.py
This PR adds type checks to the library and implements changes requested by the static type checker `mypy`. Eventually, it will also add `mypy` to the CI.
Note: This is a draft PR and was created now to raise awareness of this. To run `mypy`, execute:
```
pip install mypy
cd gp/
mypy *.py
```
This will currently raise a bunch of errors that need to be addressed before this PR can get merged. Also, the current state of the code introduces a circular import which will make importing the library fail.
=> Add type checks

gp/ea/mu_plus_lambda.py, gp/hl_api.py, test/test_ea_mu_plus_lambda.py, test/test_utils.py
As far as I can see this functionality is not necessary and can be easily be replaced by a call to `functools.partial`, no need to maintain this additional complexity.
fixes #104
=> Remove unnecessary "label" arg from `evolve` and `MuPlusLambda`

examples/example_caching.py, gp/utils.py, test/test_utils.py
This PR makes the caching decorator naturally work with multiprocessing without the need for manual cache checking at the expense of removing an additional check for consistency of (keyword) arguments of decorated functions.
Note that this is a different, in my opinion cleaner and more user friendly, implementation than those discussed in #86 and #91.
closes #91
=> Check cache consistency on first decoration, not on first call

gp/genome.py, gp/primitives.py, setup.py, test/conftest.py, test/test_cartesian_graph.py, test/test_genome.py, test/test_hl_api.py, test/test_individual.py, test/test_local_search.py, test/test_node.py, test/test_node_factories.py, test/test_population.py, test/test_primitives.py
Instead of using an `OrderedDict` like suggested in #107 this PR replaces the dictionary used in `Primitives` with a list. Since function keys are just integers, they might as well be indices in an array. This automatically avoid a potential relabeling of functions when a `Primitives` object is converted to a list a reinitialized.
Also renames `Primitives.sample` -> `Primitives.sample_allele`.
Also removes some outdated comments.
closes #107 
closes #106
=> Replace dictionary in Primitives with tuple and turn Primitives into frozen dataclass

gp/ea/mu_plus_lambda.py, gp/local_search/gradient_based.py, test/test_local_search.py
=> Change local search to accept single not list of individuals

.travis.yml, cgp/cartesian_graph.py, cgp/local_search/gradient_based.py, setup.py, test/test_individual.py
This PR adds jobs to the CI that test the libraries without extra requirements. Closes #103 and fixes the detected issues:
- put annotations using optional dependencies in quotation marks
- mark torch- and sympy-dependent tests as skip
It furthermore fixes some minor issues with flake8 and makes `coveralls` actually look at the library, not at the tests.
=> Modify travis config file to add job matrix

cgp/cartesian_graph.py, cgp/genome.py, cgp/individual.py, test/test_individual.py, test/test_local_search.py
As discussed in #97. This dictionary is used to store the values for ParameterNodes appearing in the graph. It is hence closely linked to the specific genome and should hence be managed there.
closes #97
=> Move parameter_names_to_values from Individual to Genome

cgp/individual.py
as discussed on slack, this moves all functionality from the derived classes into the base class where static methods which operate on `Genome` are defined. might seem to be too many indirections, e.g., `to_func -> _to_func -> to_func` but this makes the derived classes trivial to understand as they only call the static methods on each of their `Genome` members. note that here `__repr__` is missing. `crossover` was intentionally deleted to remove dead code.
=> Move all shared functionality from IndividualSingle/MultiGenome to base class

cgp/individual.py, cgp/population.py, test/test_hl_api.py, test/test_population.py
apparently one can drop the annotations in the parent class, functions only need to have the same signature, not typing. this resolves the mypy issues. i've also removed a function that i think we never used but which caused annoying mypy problems. also fixed the tests.
=> Fix mypy issues by defining methods in parent class without typing

cgp/ea/mu_plus_lambda.py, cgp/hl_api.py, cgp/individual.py, cgp/local_search/gradient_based.py, cgp/population.py, test/conftest.py, test/test_cartesian_graph.py, test/test_ea_mu_plus_lambda.py, test/test_genome.py, test/test_hl_api.py, test/test_individual.py, test/test_local_search.py, test/test_utils.py
This PR adds type hints to the `Individual` and `IndividualMultiGenome` classes and fixes the detected issues:
1. `Individual` and `IndividualMultiGenome` class
The relation between the two classes was not good: Having IndividualMultiGenome inherit from Individual causes problems. For instance, the self.genome member is a list of Genome instances in the former, but since it is initialized in the latter as a Genome instance, this does not make much sense. We could refrain from calling the super().__init__() function but then the inheritance does not make any sense. 
*Solution*: As discussed below, I removed the `IndividualMultiGenome` class and make the `self.genome` member of `Individual` a list. This triggered some changes in the `Population` class and the local search algorithms which …
=> Add type hints to Individual class and fix detected issues

cgp/cartesian_graph.py, test/test_cartesian_graph.py
These kind of problems should not be caught but propagated to the user who will know how to deal with them appropriately. This specific case is even worse: since the `InvalidSympyExpression` is only defined locally in `_validate_sympy_expr`, we can't even catch that specific expression outside on the user level, forcing us to use a catch all.
=> Avoid catching of SymPy expression

cgp/individual.py, test/test_local_search.py
This PR adds a test for local search with `IndividualMultiGenome` and fixes but in the `update_parameters_from_torch_class` function.
The bug was tricky: We called `any()` on a generator. However, it turns out that if do that, then the iteration stops once the condition inside `any()` has been evaluated to `True` once. That makes sense since `any()` will return `True` if any of the conditions is `True`, i.e., there is no point in continuing after finding one evaluation to `True`. 
Obviously, this is not what we want here, because all the genomes should update their parameters. Thus, I turned the generator into a list comprehension to make sure that all genomes are updated.
The test extends the test for `IndividualSingleGenome` by using two genomes and defining the loss function such that …
=> Fix bug in IndividualMultiGenome and add test

setup.py
also cleans up reading of required requirements using the same structure as reading extra requirements
fixes #144
=> Cut version number from keys in extra_requirements dict

README.md
Add installation instructions to README. 
Note: I noticed that installing extra requirements is tedious at the moment. See #144 
Add citation and DOI badge to README.
=> Add installation instructions and citation to README

.travis.yml
This PR adds the examples to the CI. Note that the examples require the extra requirements, therefore we cannot run the examples in all jobs.
Discussion point: Perhaps it's sufficient to run the examples in one Python version?
Fixes #122
=> Add examples to CI

examples/example_mountain_car.py
This example demonstrates how to solve an Open AI Gym environment with CGP. Fitness function is based on empirical observations to maximize solving speed. Found solution is almost always of the form `c \dot x`, sometimes `c \dot x - x` for that last bit of efficiency (try it!). The solution intuitively makes sense, doesn't it? ;) #interpretableRL
tagging our mountaincar expert @weidel-p
=> Add example solving OpenAI Gym MountainCarContinuous env

cgp/genome.py, examples/example_evo_regression.py, test/test_genome.py, test/test_population.py
This PR fixes the mutation counter by explicitly comparing the number of differences in dna before and after mutations
fixes #156
=> Fix counting of mutations in genome.mutate

cgp/ea/mu_plus_lambda.py, cgp/population.py, test/test_ea_mu_plus_lambda.py, test/test_genome.py, test/test_population.py
Every individual that is created or cloned is assigned a unique idx, for example, in order to be able to trace the lineage of a certain individual (to be implemented). Hopefully this PR makes the associated code a bit more transparent.
=> Refactor setting of individual idx upon creation of new individuals

cgp/ea/mu_plus_lambda.py, examples/example_differential_evo_regression.py, test/conftest.py, test/test_ea_mu_plus_lambda.py
as discussed it can be beneficial to restrict the local search to the `k` best performing individuals (#116). this PR implements this suggestion. as expected this decreases wallclock time when used, e.g., in the `example_differential_evo_regression.py` from ~57s to ~44s when running local search only for the best two individuals instead of the whole population (5 individuals).
closes #116
=> Provide possibility to restrict local search to k best individuals

cgp/ea/mu_plus_lambda.py, test/test_ea_mu_plus_lambda.py
My brain was getting too hot whenever i looked at this function. Isn't this implementation much easier? It seems that we can handle the replacement `nan` -> `-np.inf` on the fly in the function used for `key`, no need for creating a copy of the population which we modify and then argsort.
=> Simplify sorting of individuals in `mu_plus_lambda`

cgp/ea/mu_plus_lambda.py
Seems like this function can be significantly simplified. I don't think there's a danger of sharing references, as each offspring is created via clone, which avoid specifically that.
=> Simplify `create_new_parent_population` in `mu_plus_lambda`

cgp/individual.py, test/test_ea_mu_plus_lambda.py
This PR implements tracking of the parent's idx in each individual to allow the reconstruction of full lineages.
Contains changes from #167, so should be merged after.
closes #129
=> Track parent idx in offsprings, i.e., all cloned individuals

test/test_ea_mu_plus_lambda.py
=> Extend testing of MuPlusLambda class

test/test_node.py
=> Actually use `to_torch` in `_test_to_torch`

README.rst, docs/index.rst
This is a hotfix to make the image appear properly in the README again, bug was introduced in #181 .
I fixed the relative path in the README file, and changed the logic of including the header in `index.rst`: It now only includes the text, but not the image. Instead, the image is included explicitly with a correct relative path. This introduces a slight duplicate of code between README and documentation index, but this is inevitable, unfortunately. 
It is possible to use absolute paths in the README, but this will break the documentation because sphinx does not handle absolute paths. Supposedly, it should be able to (see https://stackoverflow.com/questions/52138336/sphinx-reference-to-an-image-from-different-locations), but just like for the person asking the question in that link, it …
=> Fix relative path to image in README

.travis.yml, README.rst, docs/basic_usage.rst
This fixes #184 .
First we build the documentation in one of the jobs (I simplified the command here) and place a `.nojekyll` file in the html folder (which tells github pages that we're not using jekyll as a static site builder).
In addition, the PR adds a deploy stage to travis CI, which will push the contents of `doc/_build/html` .
I followed the steps in this tutorial: https://medium.com/@FelipeFaria/sphinx-travis-ci-github-pages-full-integration-for-auto-docs-publishing-91ce93179e17
Update:
I also added a bit of simplification to the travis file:
- I refactored the documentation building line
- Instead of installing not extra requirements, we're installing the `[dev]` requirements in the last job so that we can skip the manual install of `black`, `mypy`, and `flake8`.
I also added …
=> Add deployment of documentation on github pages to CI

README.rst, cgp/ea/mu_plus_lambda.py, cgp/genome.py, cgp/population.py, examples/example_caching.py, examples/example_differential_evo_regression.py, examples/example_evo_regression.py, examples/example_mountain_car.py, test/conftest.py, test/test_ea_mu_plus_lambda.py, test/test_population.py
Since we do not support crossover and it is actually discouraged in CGP (Miller, 2011), all traces of crossover are removed. This also makes the concept of a "breeding pool" obsolete and allows us to remove the associated parameter.
closes #164
=> Remove all traces of crossover/breeding pool

test/test_utils.py
=> Use more generous bounds in test_cache_decorator, improve doc

cgp/population.py, test/test_individual.py
Adds a simple test for the `randomize_genome` function of the individual classes. All it tests is that the `randomize_genome` function does indeed change the dna.
Closes #186
=> Add test for randomize_genome function of individual classes

README.rst
Quick fix of the broken link to the Travis badge in the README. Apparently, the link is different for markdown README files and RST README files and there was a redundant `)` which led to the failing mypy badge in the docs. 
Fixes #197
=> Fix travis link in README

cgp/genome.py, cgp/population.py, test/test_ea_mu_plus_lambda.py, test/test_genome.py, test/test_hl_api.py
Implements the new logic for mutation discussed in #172. Closes #172 , #173 and makes #124 obsolete. Does not pass  `test_parallel_population` in test/test_hl_api.py, since fitnes is not the with 1 or 2 parallel processes. I created the PR anyway since I couldn't figure out why and whether this is a problem with the new logic in mutate
=> Genome mutate - implements new logic for mutations

docs/conf.py
This PR adds links to the source code to the API docs in the documentation.
To achieve, we:
- add linkcode extension of sphinx
- add linkcode_resolve function from numpy docs (see https://github.com/numpy/numpy/blob/a0028bca0117874606bce99261d978df8d3f6610/doc/source/conf.py#L332)
=> Add links to source code on github to API docs

cgp/primitives.py
This small PR adds missing annotations to `primitives.py`. This fixes #175 .
As far as I can see, the other examples mentioned in #175 have become obsolete or were already fixed. Please notify me if there are other missing annotations in the code. I did a quick check but couldn't find any other.
=> Add missing notation of return value in primitives

cgp/genome.py, test/test_genome.py
Determine permissible values per gene in initialization of genome. Addresses #196. 
I was not sure which of the `determine_permissible_value_xxx` functions should be private. And please tell me whether you think testing with the permissible values for a single genome is sufficient.
=> Permissible values per gene in initialization of genome

cgp/local_search/gradient_based.py
while clipping/thresholding values in the gradient vector can change its direction, rescaling all values to achieve a certain vector norm leaves (by definition) the orientation invariant (see, e.g., https://stackoverflow.com/questions/44796793/difference-between-tf-clip-by-value-and-tf-clip-by-global-norm-for-rnns-and-how/44798131#44798131, https://arxiv.org/pdf/1211.5063.pdf). so if we do not have a significant motivation to use `...clip_grad_value`, we should avoid using it.
=> Use norm clipping instead of value clipping to avoid changing the direction of the gradient

.travis.yml, cgp/cartesian_graph.py, cgp/node.py, examples/example_parametrized_nodes.py, test/test_node.py
With #178 this is now incredibly easy: one can just define new custom nodes that implement certain operations and may contain parameters that can be adapted via local search. This PR includes a fix for nodes that use more than one parameter and example for how to make use of the new power of #178 ;)
Should we include this parametrized add as a new default node? Or is is so simple now to define nodes that we don't need it?
closes #98
=> Allow multiple parameters for nodes and add example with parametrized additive node

cgp/genome.py, test/conftest.py, test/test_genome.py
As `mutate` uses `dna.setter` it also triggers the function to initialize numerical values for (unknown) parameters. Before initializing any parameter it is now checked that this does have a value assigned yet. If it does, this parameter is not (re)initialized.
(ouch! :grimacing: )
=> Fix parameters being reininitialized in Genome.mutate()

.travis.yml, docs/Makefile, docs/conf.py, examples/example_mountain_car.py
This PR does the following this:
- It configures sphinx such that the gallery of examples will contain the images produced by the example scripts. To that end, running `make html`  in the `docs/` folder now executes the example scripts one by one and collects the figures created by the scripts.
- To enable quick debugging of the documentation without having to run the examples every time, I introduced `make html-noplot` which skips running the examples (and produces a documentation without the figures). This is of much quicker to run.
- In the CI, I removed the step to run the examples explicitly because this is now done in the documentation build step, implicitly.
Note: It is not possible to render the openAI gym environment when running the mountain car example script with …
=> Use figures from examples in documentation

examples/example_evo_regression.py
the evo_regression example currently does not converge for the easy function (https://happy-algorithms-league.github.io/hal-cgp/auto_examples/example_evo_regression.html#sphx-glr-auto-examples-example-evo-regression-py). this PR adapts the mutation rate to make sure the example converges within the specified number of generations.
=> Reduce mutation rate in evo regression example to achieve convergence

.flake8, examples/example_differential_evo_regression.py, examples/example_evo_regression.py, examples/example_mountain_car.py, examples/example_parametrized_nodes.py, requirements.txt
This PR implements command-line args for the example scripts. It is the first step to address #208 . In a follow-up PR, I will then make use of these command-line args in the travis CI.
The following things are implemented:
- Add option to specify max_generations on the command line to example scripts
- Add switch for visualization in mountain_car example
=> Add command line args for example scripts

.travis.yml, docs/Makefile, docs/conf.py, docs/deploy.sh, extra-requirements.txt
This PR solves #208  by doing:
- Add new mode for making docs with shortened example runs
- Add class to set command line args in sphinx configuration
- Shorten example runs in Travis CI and add docs building in deployment phase
- Use specific commit of sphinx-gallery that includes the new option to specify CLI arguments (https://github.com/sphinx-gallery/sphinx-gallery/commit/387900334ace5c0bf74e9e90aad1e8d2a54e6f17)
=> Shorten execution of examples in CI

cgp/cartesian_graph.py, cgp/utils.py, examples/example_fec_caching.py, test/test_cartesian_graph.py, test/test_utils.py
This PR implements functional equivalence checking (see, e.g., https://arxiv.org/abs/2003.03384) to allow caching of (inner) objectives that are  called with individuals, not SymPy expressions. Functionally identical individuals are identified by evaluating them on a certain number of random input samples and hashing the output values.
This PR also increases the number of generations in the cache decorator example to allow evolution to converge, and adds a test that makes sure that the fitness history is identical with and without cache decorator.
~**WARNING** Currently I need to disable one other test to make the new tests pass. There is some really weird interaction on the SymPy level that I couldn't figure out yet. :|~
closes #61
=> Extend cache decorator with functional equivalence checking

docs/documentation/documentation.rst, docs/documentation/local_search.rst, docs/documentation/local_search.svg, docs/index.rst
This PR adds a page to the documentation to describe local search in our library.
I also added a sketch that compares normal evolution to evolution + local search. The figure can certainly be optimized, with regards to visual quality, but more importantly, I think it is a bit misleading that in the evolution we go from `f,g,h` --> `f',g',h' --> `f',g',h'` and then to `f,g` in the next generation. But I am not sure how to solve this, perhaps you have a good idea, @jakobj .
Otherwise, please review the text, it is quite minimal. Feel free to make suggestions.
Part of #174 .
=> Add page on local search to documentation

docs/documentation/documentation.rst, docs/documentation/local_search.rst, docs/documentation/population_individual.rst
This PR adds a page explaining the structures of CGP in our library. It is based on #220 , so only look at `population_individual.rst`. .
=> Add page explaining the structures of CGP to documentation

examples/example_multi_genome.py
This PR adds an example for multiple regression. It is based on `example_minimal.py` and modifies the target function to be piecewise defined.
=> Add example for regression with multiple genomes

cgp/cartesian_graph.py, cgp/node.py, cgp/node_input_output.py, test/test_cartesian_graph.py, test/test_node.py
This PR fixes #232 by following the suggestions of @jakobj in the ticket:
- Remove _output from repr string of Node class
- Rename _inputs to _input_nodes for better clarity
- Add test of CartesianGraph.__repr__ function
- Add test for __repr__ of 3 example nodes
=> Fix bug in Node.__repr__

cgp/individual.py, docs/documentation/population_individual.rst, test/test_individual.py
In some cases it would be nice to record some historical information within the objective function. The easiest approach would be to create a objective-function closure, similar to the history callback, and let the objective directly write to the corresponding recording object. This works well will a single process, but since parallel processes are running in different interpreter instances, it does not work with multiprocessing (at least i didn't get it to work).
Here I'm making a suggestion based on discussions with @HenrikMettler: the user can set (new) attributes of individuals within the objective which could then be subsequently recorded outside the parallel context, similar to recording, e.g., fitness values. To make this work we need to make sure offspring inherit all these custom …
=> Make sure user-set attributes of individuals are copied to offspring

cgp/cartesian_graph.py
As discussed in #231 we should catch errors thrown by sympy when calling `expr.simplify`. 
When implementing this PR I noticed that the option of the boolean `simplify = False` is never used. Maybe we could remove it altogether?
=> Catch type error in simplification

cgp/ea/mu_plus_lambda.py, cgp/hl_api.py, test/test_ea_mu_plus_lambda.py, test/test_hl_api.py
This PR draft is a suggestion for a solution to #224 
It works by counting the calls of the objective function using a decorator (as suggested eg: https://stackoverflow.com/questions/21716940/is-there-a-way-to-track-the-number-of-times-a-function-is-called). I am not sure if this is a reasonable approach, mainly two things bother me: 
- the subtraction if fitness is not reevalutated (necessary since we don't want to count those)
- if a caching decorator is used for the inner objective, the counts of the objective function calls might not correspond to full function evaluations anymore
=> Limiting fitness evaluations

cgp/__init__.py
This PR sets the version to 0.2.0 to complete the milestone and prepare for the release.
=> Bump version number to 0.2.0 to prepare for release

extra-requirements.txt
This PR replaces the explicit commit of sphinx-gallery with its release version. This is safer and also required by pypi.org to release the package.
=> Use release version of sphinx-gallery

cgp/__init__.py, cgp/cartesian_graph.py, test/test_node.py
This PR introduces a decorator which users can apply to custom functions which are then available as atomic operators in the strings defining the operation of custom nodes. Hard to explain, easy to show:
```python
@cgp.atomic_operator
def f_scale(x):
return 2.0 * x
class MyScaledAdd(cgp.node.OperatorNode):
_arity = 2
_def_output = "f_scale((x_0 + x_1))"
```
These few lines introduced a new primitive, i.e., a new node function, to CGP. This approach also works for custom atomic operators which depend on external libraries.
closes #235
=> Support custom atomic operators

cgp/ea/mu_plus_lambda.py
A persistent worker pool avoids the overhead associated with creating and destroying processes. This results in a significant speedup when function evaluations are not too expensive. For example, the minimal example runs approximately twice as fast (~11s w/ context manager, ~5s w/ persistent pool). For a larger number of processes this difference becomes larger.
=> Use a persistent process pool instead of a context manager

cgp/ea/mu_plus_lambda.py, cgp/individual.py, cgp/population.py, examples/example_caching.py, examples/example_differential_evo_regression.py, examples/example_evo_regression.py, examples/example_fec_caching.py, examples/example_hurdles.py, examples/example_mountain_car.py, examples/example_multi_genome.py, examples/example_parametrized_nodes.py, examples/example_piecewise_target_function.py, examples/example_reorder.py, test/test_ea_mu_plus_lambda.py, test/test_hl_api.py, test/test_individual.py, test/test_local_search.py
This PR suggests an implementation that allows users to specify hurdles. Hurdles effectively implement early stopping for poorly performing individuals. The implementation allows users to pass lists of objectives to the EA/hl API and to define the "hurdle percentile" as a parameter of the EA for each of the objectives. Only individuals achieving fitness in the upper "hurdle percentile" of the _unique_ fitness values of the _whole_ population (parents + offspring) for the first objective are evaluated on the second objective, and so on.
An example is provided as extension of the minimal example (docstrings are yet to be adapted), where the performance difference is quite visible when considering a large number of function evaluations (28s w/o hurdles, 11s with hurdles on an i5-8350U). …
=> Provide support for hurdles

cgp/genome.py, test/test_node.py
For suboptimal expressions, for example at the beginning of the evolution, the local search can lead to abnormally large parameter values. If these value persist across all generations, the corresponding parameterized nodes may never be used in the final expression: as soon as they are included, the (initially set) large parameter values may lead to poor fitness.
This PR adapts the mutation step such that when a node with parameters is created, the corresponding values are reset to the initial values specified by the user in the definition of the node. This should avoid the issue described above.
=> Reset parameters when the corresponding node is created by mutation of a genome

cgp/utils.py, examples/example_fec_caching.py, setup.py, test/test_utils.py
This PR improves the disk cache decorator:
- the cache file consists of a single large dict containing (key: fitness) pairs; no need for a linear search through keys to find a match
- function arguments are now only stored for a single function call to support consistency checks; this avoid unnecessarily large cache files by storing arguments for each(!) result
- for using multiple processes, a lock is introduced to make sure they are reading from/writing to the cache file without interference
=> Improved caching decorator

cgp/genome.py, test/test_genome.py
Fixes the bug found in #261. Replaces the names in 'parameter_names_to_values' with the updated names (-> addresses). 
The updated test currently fails after some reorderings - I can't understand why, help would be appreciated (I added some lines for debugging to make the error more understandable)
=> Bug-fix: Reorder changes phenotype for individuals with parameters (#261)

cgp/cartesian_graph.py, cgp/node.py, test/test_cartesian_graph.py, test/test_node.py
There does not seem to be any need for calling the graph object directly. As soon as more than a single call is required, the `to_...` versions are much faster as they only require traversing the cartesian graph once.
This PR hence removes support for this functionality to i) prevent users from accidentally making their code slow and ii) relieve us of the burden of maintaining it.
=> Remove support for calling graph directly

cgp/cartesian_graph.py
The current error message can be a bit confusing as we are trying to guess the batch dimension. If someone provides a transposed array with shape, e.g., (2, 200) to a graph with two inputs, the message claims the input should have shape (2, 2), while the correct size would be (200, 2).
This PR changes the error message to avoid such confusing output.
=> Fix error message wrong size passed to to_torch/to_numpy graphs

cgp/utils.py, test/test_utils.py
This PR fixes a bug in the fec cache where only the evaluation of the function encoded in an individual would determine the cache key, while all other (keyword)arguments would be ignored. This means that calls like this for a decorated inner objective:
```python
y0 = inner_objective(ind, 5)
y1 = inner_objective(ind, 10)
```
would yield the same values as the second one is assigned the same key and hence the cached value is returned.
=> Also use all args and kwargs when computing fec cache key

cgp/ea/mu_plus_lambda.py, examples/example_hurdles.py, examples/example_minimal.py, examples/example_multi_genome.py, examples/example_piecewise_target_function.py, examples/example_reorder.py, test/test_ea_mu_plus_lambda.py
Makes the sanity check that the tournament size is smaller or equal to the number of parents in a population. Closes #246 
Note that this PR is not ready for merging - due to the sanity checks various examples now raise errors. (Will adapt if the concept is approved)
=> Check tournament_size <= n_parents in hl_api

cgp/genome.py, cgp/node_validation.py, test/test_cartesian_graph.py, test/test_genome.py, test/test_individual.py, test/test_local_search.py, test/test_node.py
Addresses #276. There is one minor thing: The current checks allow `n_columns=0` and set `levels_back=n_columns` (if None provided), but they don't allow `levels_back=0` 
This could lead to confusing error messages
=> Make levels_back parameter optional

cgp/utils.py, examples/example_caching.py, examples/example_fec_caching.py, test/conftest.py, test/test_utils.py
Currently the user can choose between computing a key for the disk cache all arguments and keyword arguments to the decorated function or from the result of evaluating an individual on random numpy arrays and the remaining arguments and keyword arguments.
This PR allows users to specify a function that is used to compute the key for the cache. Two functions are provided by the library: one uses the sympy expression of an individual and the remaining arguments, one the results of evaluating the individual on random numpy arrays and the remaining arguments. In addition the user can define any custom function they like provided its first argument is an individual instance and its return value is a float.
=> Allow custom functions to be used for computing cache keys

cgp/ea/mu_plus_lambda.py, cgp/genome.py, cgp/individual.py, cgp/local_search/__init__.py, cgp/local_search/evolution_strategies.py, examples/example_local_search_evolution_strategies.py, test/test_genome.py, test/test_ls_evolution_strategies.py
This PR implements separable natural evolution strategies (https://jmlr.org/papers/volume15/wierstra14a/wierstra14a.pdf) as a local search algorithm. Tests and an example are provided.
To get everything working smoothly, I needed to make sure outcomes of the local search are only accepted if they indeed increase the fitness of the respective individual (https://github.com/Happy-Algorithms-League/hal-cgp/compare/master...jakobj:enh/local-search-es?expand=1#diff-e76e9c33f502310da4d066b5ee5bd4e34e475e453c754ed908f19f34e4afef19R140 ff). Thereby closes #215.
Please review in particular with respect to ease of use and maintainability.
closes #146
=> Implement local search that does not require differential objectives -- evolution strategies

README.rst
=> Improve description of design/use cases

cgp/__init__.py, cgp/hl_api.py, examples/example_caching.py, examples/example_differential_evo_regression.py, examples/example_evo_regression.py, examples/example_fec_caching.py, examples/example_hurdles.py, examples/example_local_search_evolution_strategies.py, examples/example_minimal.py, examples/example_mountain_car.py, examples/example_multi_genome.py, examples/example_parametrized_nodes.py, examples/example_piecewise_target_function.py, examples/example_reorder.py, test/test_hl_api.py
I discovered that `min_fitness` is currently a positional argument. Shouldn't it be optional? Why is the user forced to always set it?
I made it optional in this PR, but if there is a good reason to have it as a positional arg, I am happy to revert this change.
I didn't completely remove `min_fitness` to not break the API. The idea is to remove it in the next major release (1.0 ?).
Add DeprecationWarning for min_fitness
Add assertion that min_fitness and termination_fitness are not both defined
Make both args optional
Add test
Closes #289
=> Replace min_fitness by termination_fitness

cgp/individual.py
=> Add annotation in Individual

.readthedocs.yaml, extra-requirements.txt
Activate building the documentation to migrate from github pages to readthedocs. This supports multi-version building. After merging this PR, I will create another PR to replace the link in the README and then close the associated ticket #251 after that.
=> Add readthedocs config file and requirements for docs

README.rst
Small PR to replace the Travis CI badge in the README by the github actions badge.
=> Change CI badge from travis to github actions

cgp/cartesian_graph.py, cgp/node_impl.py, cgp/node_input_output.py, cgp/node_validation.py, cgp/utils.py, examples/example_caching.py, examples/example_differential_evo_regression.py, examples/example_evo_regression.py, examples/example_fec_caching.py, examples/example_hurdles.py, examples/example_local_search_evolution_strategies.py, examples/example_minimal.py, examples/example_mountain_car.py, examples/example_multi_genome.py, examples/example_parametrized_nodes.py, examples/example_piecewise_target_function.py, examples/example_reorder.py, test/test_cartesian_graph.py, test/test_ea_mu_plus_lambda.py, test/test_hl_api.py, test/test_individual.py, test/test_ls_evolution_strategies.py, test/test_node.py, test/test_utils.py
This PR aims at making the usage of the results from various `to_...` functions more intuitive. It also improves their documentation. In the following the new usage is described in more detail.
`to_func` -> f:
- f expects the same number of arguments as the graph has input
- each argument must be a single value
- f returns a list of values, one for each output
- if only one output is present it'll return only it's output value; _not_ a list with one entry
example usage:
```python
f = ind.to_func()
y = f(1.0, 2.0)
```
`to_numpy` -> f:
- f expects the same number of arguments as the graph has input
- each argument must be a single numpy array of identical lengths
- f returns a list of arrays, one for each output; each array will have the same length as all input arrays
- if only one output …
=> Redesign signatures of compilation targets

test/test_genome.py, test/test_population.py
So, weirdly `n_columns = 0` works in the minimal example and in a small test in population it gives the expected sympy expression. However a lower level test fails when calling directly `CartesianGraph(genome).to_sympy()`. Any ideas why? 
Also imo we should rather deprecate the `n_columns=0` or `n_rows=0` functionality, since they don't make much sense anyway. 
Closes #283
=> Testing `n_columns=0`

.github/workflows/tests.yaml, README.rst, cgp/ea/mu_plus_lambda.py, cgp/genome.py, cgp/hl_api.py, cgp/individual.py, cgp/local_search/evolution_strategies.py, extra-requirements.txt, requirements.txt, setup.py, test/test_hl_api.py
This PR makes hal-cgp compatible with Python 3.9 and removes support for python 3.6. 
To that end, several dependencies are updated, most importantly numpy  to version 1.20 which supports python 3.9. That led to a cascade of errors signaled by mypy which are fixed in this PR:
- many are mismatches between return types and variable types
- numpy now supports type hints internally. This leads to a problem with our type hints which specify a dtype for arrays. As far as I understand, before, mypy just did not check those at all. Now, mypy checks them, but numpy does not support hints for dtypes yet, so this threw an error. I fixed it by removing all dtypes from the array type ints.
- mypy now correctly complained about the type hint in the high-level api that defines e.g. `max_generations` as …
=> Support Python 3.9, drop Python 3.6 support, update requirements

test/test_ea_mu_plus_lambda.py
Fixes the bug introduced by merging #333 (with wrong argument order for call to cgp.evolve)
=> Bugfix argument order in new test

cgp/utils.py, test/test_utils.py
As the title suggests: to avoid difficult-to-debug bugs this PR restricts the types which can be used as arguments to functions decorated with the caching decorator. At the moment these are restricted to: `str, int, float, tuple, list, np.ndarray, dict`. This list can be extended as necessary.
fixes #325
=> Restrict argument types to decorated functions

cgp/ea/mu_plus_lambda.py, cgp/individual.py, test/test_ea_mu_plus_lambda.py, test/test_individual.py
As the title says. Introducing this test unearthed a bug in the sorting of individuals in the case of multiple objectives (used with hurdles) which this PR also fixes: individuals should be sorted according to their fitness values, starting from the _last_ objective, whereas previously they were sorted starting from the _first_ objective. Behind this underlies the assumption that later objectives (in terms of hurdles) are more informative about the quality of an individual.
closes #342
=> Add test for sorting of individuals, fix bug in sorting

test/test_utils.py
The reason for the the slow process startup time in OS11 (#349) for the ProcessPoolExecutor is the use default use of spawn as a start method on macOS (see: https://docs.python.org/3/library/multiprocessing.html). Explicitly setting the context as fork removes the issue.
=> Use fork as explicit context for ProcessPoolExecutor in test

cgp/cartesian_graph.py, cgp/individual.py, cgp/utils.py, extra-requirements.txt, test/test_utils.py
As the title suggests: If no finite value is returned from the numpy evaluation, two functions which are indeed different could result in the same key. This PR introduces a check which raises an exception if such a situation is encountered.
fixex #350
=> Make sure that at least one value is finite for computing key in caching decorator

.github/workflows/tests.yaml, extra-requirements.txt
As the title suggests.
closes #363
=> Refine github workflow and freeze some packages

cgp/hl_api.py, test/test_hl_api.py
When objects are created this way they will be persistent across multiple invocations of the associated function running in the same interpreter session. This can have annoying side effects.
branches from #368 so should be merged after
closes #353
=> Don't create objects via default function parameters in hl api
